SET NAMES utf8mb4;

-- Seed a default unit; users are auto-seeded by the app on first run if empty
INSERT INTO units (name, code) VALUES ('Head Office', 'HO');
-- Seed glossary (sample coal-industry terms)
INSERT INTO glossary (term_hi, term_en, category) VALUES
('कोयला', 'Coal', 'general'),
('खनन', 'Mining', 'operations'),
('उत्पादन', 'Production', 'operations'),
('परिवहन', 'Transport', 'logistics'),
('भंडारण', 'Storage', 'logistics'),
('क्षेत्र', 'Area', 'org'),
('विभाग', 'Department', 'org'),
('रिपोर्ट', 'Report', 'admin'),
('अनुमोदन', 'Approval', 'admin'),
('अस्वीकृति', 'Rejection', 'admin'),
('कर्मचारी', 'Employee', 'hr'),
('प्रशिक्षण', 'Training', 'hr'),
('प्रतिभागी', 'Participants', 'hr'),
('द्विभाषी', 'Bilingual', 'language'),
('हिंदी', 'Hindi', 'language'),
('अंग्रेजी', 'English', 'language'),
('प्रतिशत', 'Percent', 'metrics'),
('तिमाही', 'Quarter', 'metrics'),
('लंबित', 'Pending', 'status'),
('स्वीकृत', 'Approved', 'status');


-- Optionally, pre-create users by importing password hashes generated by PHP password_hash.
-- If left empty, the application will create the following users automatically at first run:
--   admin@example.com / Admin@123 (super_admin)
--   officer@example.com / Officer@123 (officer)
